### PR TITLE
monorepo-utils: sanitize shell output of "yarn workspaces info"

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**
fixes https://github.com/adeira/universe/issues/436

### CODE REVIEW

**Comment by tbergq** [comment]
Though this probably fixes this issue with `yarn workspaces info --json`, this could happen with other scripts using `ShellCommand`and getting stdout, so it would be interesting to find out why it is including the rest of the output when it is run with `node` rather than with `yarn mononrepo-babel-node`

**Comment by jaroslav-kubicek** [comment]
AFAIK it's how yarn behaves, when you run `yarn workspaces info --json` you get exactly the same, quite unfortunate since you are asking for json, so it's not `ShellCommand` problem, only this particular case.

**Comment by tbergq** [comment]
But somehow, when you create a file with `ShellCommand(null, 'yarn', 'workspaces, 'info', '--json')`

And run that file with `yarn monorepo-babel-node file.js`, I would like to know why that works, and `node file.js` does not.

**Comment by jaroslav-kubicek** [comment]
alright, I think I got that 😅

**Comment by mrtnzlml** [comment]
> alright, I think I got that 😅

Do you know what is the problem? Sounds like a bug in Yarn since `yarn workspaces info --json` and `yarn workspaces info` returns the same output. 🤔

**Comment by tbergq** [comment]
> > alright, I think I got that 😅
> 
> Do you know what is the problem? Sounds like a bug in Yarn since `yarn workspaces info --json` and `yarn workspaces info` returns the same output. 🤔

It seems the correct usage is `yarn --json workspaces info`

**Comment by mrtnzlml** [comment]
@tbergq That sounds like a solution to our problem.

**Pull request merged**
