### PR TITLE
Make docs work again, remove blog

### PR DESCRIPTION
**Pull request by mrtnzlml**

### CODE REVIEW

**Comment by jaroslav-kubicek** [comment]
I would change also algolia settings to use different client https://github.com/adeira/universe/pull/14/files#diff-ca2cac1af1f122a3d5b210718b6f5a85R74

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek How should I update it? Should we probably remove the whole Algolia for now? They could provide us the whole search when we are done with the changes for free (see my website).

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek OK changed, please have a look.

**Comment by jaroslav-kubicek** [comment]
rebase is needed @mrtnzlml

**Pull request merged**
