### PR TITLE
CI: add cache for Flow saved state

### PR DESCRIPTION
**Pull request by mrtnzlml**
Closes: https://github.com/adeira/universe/issues/1078

### CODE REVIEW

**Review by tbergq — APPROVED** [review]

**Comment by tbergq** [comment]
Actually, I don't think it works to use `hashFiles` on a gitignored file

**Comment by tbergq** [comment]
> Actually, I don't think it works to use `hashFiles` on a gitignored file

Since it says `Cache restored from key: Linux-flow-`, there is no hash there

**Comment by mrtnzlml** [comment]
@tbergq So how should it be? Just without the `hashFiles` and without the `restore-key`?

**Comment by tbergq** [comment]
I really don't know. If the cache key doesn't change, but the file itself changes, the changed file is not uploaded to the remote cache which is not what we want. Maybe artifacts are better here?

**Comment by mrtnzlml** [comment]
Mm, seems like we cannot cache it now on Github CI (https://github.com/actions/cache/issues/106). Closing for now.

**Pull request closed without merging**
