### PR TITLE
SX: add failing test for nested media queries

### PR DESCRIPTION
**Pull request by mrtnzlml**
We are currently generating media queries on a global level but they should stay nested. See: https://www.w3.org/TR/css3-conditional/#processing

### CODE REVIEW

**Comment by tbergq** [comment]
Looks like we need a smarter way to pass down the current style buffer 🙈

**Comment by mrtnzlml** [comment]
@tbergq Or perhaps change the whole structure of it and make it more advanced. It's currently very very simple.

**Comment by tbergq** [comment]
Yeah, that is probably possible as well 👍

**Comment by mrtnzlml** [comment]
Support added in SX version 0.10.0 - closing.

**Pull request closed without merging**
