### PR TITLE
monorepo-utils: Correctly log timezone

### PR DESCRIPTION
**Pull request by tbergq**
Currenlty it was logging UTC, even if you had another
timezone in process.env.TZ

### CODE REVIEW

**Comment by mrtnzlml** [comment]
These timezones work a bit differently. There are 3 timezones available and cannot really be changed:

```js
const timezones = [
  'UTC',
  'Asia/Tokyo', // +9
  'America/Lima', // -5
];
```

The idea was, that you run the tests with `parallel:3` in GitLab and it automatically runs them in these timezones to verify everything works as expected (see `process.env.CI_NODE_TOTAL` and `process.env.CI_NODE_INDEX`).

**Comment by tbergq** [comment]
Yes, well, I tried to run them locally in another project with `TZ=America/Lima yarn test` and it kept logging `Running tests in timezone UTC` which was very confusing

**Comment by tbergq** [comment]
Because the test was actually run in the correct timezone, just the log was wrong.

**Comment by mrtnzlml** [comment]
> Because the test was actually run in the correct timezone, just the log was wrong.

I believe this is an unintentional bug that turned into a feature... 😅

**Comment by tbergq** [comment]
> > Because the test was actually run in the correct timezone, just the log was wrong.
> 
> I believe this is an unintentional bug that turned into a feature... 😅

Intentionally or not, It is nice to be able to run tests in the timezone of your choice locally

**Pull request merged**
