### PR TITLE
Rename js to @adeira/js

### LINKED ISSUE #6: Rename @adeira/js

### PR DESCRIPTION
**Pull request by tbergq**
closes #6

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Oh no, I resolved conflicts via GitHub UI and I probably messed up this PR. I will check later if you don't fix it before me.

**Comment by tbergq** [comment]
I am not able to see where this PR is messed up, and pipeline passes.

**Comment by jaroslav-kubicek** [comment]
@mrtnzlml you clicked on that GitHub grey button, don’t you? It merged master into this branch. I would recommend to ignore that button to not mess with the history

**Comment by tbergq** [comment]
Aha, the merge commit 🙈

**Comment by tbergq** [comment]
Should be fixed now.

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Maybe, I clicked to "resolve conflicts" button (not the "update branch") and resolved the conflicts manually in the browser. This: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Pull request merged**
