### PR TITLE
Relay: Fetch schema script options fix

### LINKED ISSUE #1814: @adeira/relay: unable to use 'adeira-fetch-schema' script
To reproduce:

```bash
yarn adeira-fetch-schema --resource …
```

Throws:

```text
Invariant Violation: Option --resource is required.
```

### PR DESCRIPTION
**Pull request by michalsanger**
Fix #1814

### CODE REVIEW

**Review by mrtnzlml — APPROVED** [review]

**Comment by mrtnzlml** [comment]
I am wondering if there is an easy way how to test this? 🤔 It probably broke with some dependency breaking change upgrade.

**Comment by michalsanger** [comment]
I wish I had an idea how to test it :-(

**Comment by mrtnzlml** [comment]
OK, no problemo. Thanks for the fix.

**Comment by tbergq** [comment]
> I am wondering if there is an easy way how to test this? 🤔 It probably broke with some dependency breaking change upgrade.

I had an idea about doing something like: 

```js
spawnSync(
    'node',
    [
      require.resolve('../fetch-schema'),
      `--filename=${path.relative(
        findMonorepoRoot(),
        require.resolve('../__fixtures__/test.graphql'),
      )}`,
      `--resource=https://www.test.gql`,
    ],
    { stdio: 'inherit', cwd: findMonorepoRoot() },
  );
```

and use `msw` or mock fetch and read the file it writes and assert it as a snapshot. 

```js
expect(
    fs.readFileSync(path.join(__dirname, '..', '__fixtures__', 'test.graphql'), 'utf-8'),
  ).toMatchSnapshot();
```

but that didn't work, since I spawn a new process and neither msw or the mocked fetch exists in that new process.

**Comment by tbergq** [comment]
Actually, I might have found a way to make it work. I will see if I can clean it up tomorrow.

**Comment by mrtnzlml** [comment]
Such a high-level integration test might not be necessary. After all, the issue was that we were using `commander` incorrectly, and could not retrieve the CLI options. It would be enough to do something like this to prevent this issue in the future: https://github.com/tj/commander.js/blob/4aaaa9de3fd09401afe3894483193ba0e2e512d7/tests/args.literal.test.js#L9-L18 (so simply extract the options definition and try to parse some fake command, no need to run the whole fetcher). The second follow-up of this PR should be to install Flow types for `commander` from `flow-typed`. Does anyone want to do it? 😊

**Pull request merged**
